apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: observability
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: us-central1-docker.pkg.dev/teak-proton-472112-q0/docker/autoinstrumentation-java:2.19.0
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=dev"
