---
# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    app.kubernetes.io/component: observability

---
# 2. ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent
  namespace: observability
  labels:
    app: otel-agent
    component: agent

---
# 3. ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-agent
  labels:
    app: otel-agent
    component: agent
rules:
  # Required for Kubernetes Attributes Processor
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/stats
      - services
      - endpoints
      - pods
      - events
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  # Non-resource URLs
  - nonResourceURLs:
      - "/metrics"
      - "/stats"
    verbs: ["get"]

---
# 4. ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-agent
  labels:
    app: otel-agent
    component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-agent
subjects:
  - kind: ServiceAccount
    name: otel-agent
    namespace: observability
# 5. otel-agent-config 6. otel-agent-daemonset
---
# 7. Service - For health checks and monitoring
apiVersion: v1
kind: Service
metadata:
  name: otel-agent
  namespace: observability
  labels:
    app: otel-agent
    component: agent
spec:
  type: ClusterIP
  clusterIP: None # Headless service
  selector:
    app: otel-agent
    component: agent
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
# ---
# # 8. PodDisruptionBudget
# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: otel-agent-pdb
#   namespace: observability
#   labels:
#     app: otel-agent
#     component: agent
# spec:
#   minAvailable: 3  # At least 1 agent must be available (adjust based on cluster size)
#   selector:
#     matchLabels:
#       app: otel-agent
#       component: agent

# ---
# # 9. PriorityClass
# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: otel-agent-priority
#   labels:
#     app: otel-agent
#     component: agent
# value: 1000000  # High priority (system-cluster-critical is 2000000000)
# globalDefault: false
# description: "Priority class for OTel agent DaemonSet to prevent eviction"
