# 6. DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: observability
  labels:
    app: otel-agent
    component: agent
spec:
  selector:
    matchLabels:
      app: otel-agent
      component: agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: otel-agent
        component: agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: otel-agent
      # hostNetwork: true  # Use host network so apps can reach via NODE_IP
      # dnsPolicy: ClusterFirstWithHostNet
      # priorityClassName: otel-agent-priority
      
      containers:
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:0.136.0
        imagePullPolicy: IfNotPresent
        
        command:
          - "/otelcol-contrib"
          - "--config=/conf/otel-agent-config.yaml"
        
        ports:
        - name: otlp-grpc
          containerPort: 4317
          hostPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          hostPort: 4318
          protocol: TCP
        - name: metrics
          containerPort: 8888
          protocol: TCP
        - name: healthcheck
          containerPort: 13133
          protocol: TCP
        - name: zpages
          containerPort: 55679
          protocol: TCP
        
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      
      volumes:
      - name: otel-agent-config-vol
        configMap:
          name: otel-agent-config
          items:
          - key: otel-agent-config.yaml
            path: otel-agent-config.yaml
      
      # tolerations:
      # - effect: NoSchedule
      #   operator: Exists
      # - effect: NoExecute
      #   operator: Exists
